baseURL = "https://sachamasry.com/"
languageCode = "en-gb"
title = "Sacha El Masry"
theme = "hugo-resume"

[params]
    firstName = "Nabil"
    middleName = "Sacha"
    lastName = "El Masry"
    address = "Toronto, Canada"
    phone = ""
    contactNote = "Marketer"
    profileImage = "img/sacha-el-masry-Kingsly-square profile.jpg"
    email = "contact@sachamasry.com"
    description = "Marketer | Business process automation specialist | Technology entrepreneur | Web developer | Tango dancer."
    favicon = "favicon/favicon.ico"
    # what sections
    showSkills = false
    showProjects = false
    showOpenSource = false
    showPublications = false
    showArticles = true
    showExperience = false
    showEducation = false

    showQr = false

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/sachamasry/"


# [[params.handles]]
#     name = "GitHub"
#     link = "https://github.com/eddiewebb/"
